[advisories]
yanked = "deny"

# A list of advisory IDs to ignore. Note that ignored advisories will still
# output a note when they are encountered.
ignore = [
]

[licenses]
allow = [
    "Apache-2.0 WITH LLVM-exception",
    "Apache-2.0",
    "GPL-3.0",
    "ISC",
    "LGPL-2.1",
    "MIT",
    "Unicode-3.0",
    "Zlib",
]
